### ISSUE TITLE
oXygen installation

### ISSUE THREAD

**Issue by OS-50101** [schematron-quickfix/escali-package#8]
I tried to install the add-opn in oXygen (20.1) via the links
https://github.com/schematron-quickfix/escali-package/tree/master/escaliOxygen
and
https://github.com/schematron-quickfix/escali-package
also
donwloaded the repository and tried with the pom.xml.

All above failed.

**Comment by nkutsche** [comment]
Hi,

did you used this URL `https://raw.githubusercontent.com/schematron-quickfix/escali-package/master/escaliOxygen/build/extensions.xml` as update site in Oxygen as it was described under your mentioned first link?

_If not_ please try this. 

_If yes_ please provide me more information about the error or unexpected behavior.

**Comment by OS-50101** [comment]
Ok, sorry, I didn't noticed the URL in the  **Installation**, now it worked for me.

Are there any User Guide for add-on? Intuitively I couldn't figured out how to use it. I could only open _Options_ ; other buttons are inactive


![image](https://user-images.githubusercontent.com/24490898/51523930-110df600-1e2d-11e9-9404-b27bfd7dfe5d.png)

**Comment by nkutsche** [comment]
Please have a look at the first hint, I gave in #9. Maybe it helps to start.
